export const BANDI_STATUS = {
  IN_CUSTODY: 1,
  RELEASED_ON_PAROLE: 2,
  RELEASED_ON_BAIL: 3,
  PAROLE_VIOLATION: 4,
  NEW_CRIME: 5,
  ESCAPED: 6,
  RE_ARRESTED: 7,
  DECEASED: 8,
  SENTENCE_COMPLETED: 9,
};
